services:
  # PostgreSQL Database (Different port and database name)
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: real_estate_db_copy
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"  # Different port to avoid conflict
    volumes:
      - postgres_data_copy:/var/lib/postgresql/data
    networks:
      - rag-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d real_estate_db_copy"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache (Different port)
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"  # Different port to avoid conflict
    networks:
      - rag-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ChromaDB for document embeddings (Different port)
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8004:8000"  # Different port to avoid conflict
    volumes:
      - chroma_data_copy:/chroma/chroma
    networks:
      - rag-network

  # FastAPI Backend
  backend:
    build: ./backend
    ports:
      - "8002:8001"  # Different port to avoid conflict
    env_file:
      - ./backend/.env.docker
    environment:
      - DATABASE_URL=postgresql://admin:password123@postgres:5432/real_estate_db_copy
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379/0
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - REELLY_API_KEY=${REELLY_API_KEY}
      - SECRET_KEY=dubai-real-estate-rag-secret-key-2024-copy
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      chromadb:
        condition: service_started
    volumes:
       - ./backend:/app
    networks:
      - rag-network
    restart: unless-stopped

  # React Frontend
  frontend:
    build: ./frontend
    ports:
      - "3001:3000"  # Different port to avoid conflict
    environment:
      - REACT_APP_API_URL=http://localhost:8002
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - rag-network
    restart: unless-stopped

volumes:
  postgres_data_copy:
  chroma_data_copy:

networks:
  rag-network:
    driver: bridge
